### ISSUE TITLE
August 2017 Team Meeting Agenda Topics

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/governance#36] opened 2017-08-28 13:55 UTC
To help us quickly collect topics for our August 2017 team meeting, please enter comments and upvote existing comments. We are short on time (only two days), so this will help us to surface the most pressing discussion topics.

https://paper.dropbox.com/doc/August-2017-Team-Meeting-Agenda-NvwrkTa47sUQJbRjDwfzN

**Comment by Carreau** [comment] 2017-08-28 13:57
I think we should make a JupyterCon debrief while still fresh in our heads.

**Comment by rgbkrk** [comment] 2017-08-28 13:57
Notebook HTML and JavaScript mimetypes

**Comment by choldgraf** [comment] 2017-08-28 14:05
Use-cases/ways to highlight tools in the Jupyter ecosystem. Ideas to build documentation and demos. (in particular for the newer tools like JupyterHub and JupyterLab)

**Comment by damianavila** [comment] 2017-08-28 14:08
Roadmap updates/upgrades (and with better definition/accuracy) so everyone could know about our next steps and can plan accordingly.

**Comment by ellisonbg** [comment] 2017-08-28 14:11
What to do with our roadmap:

https://github.com/jupyter/roadmap

**Comment by bollwyvl** [comment] 2017-08-28 14:12
UI, Metadata, and Tools for Internationalization/Localization of Notebooks

> building on [the existing core JEP](https://github.com/jupyter/enhancement-proposals/pull/16)

- what can be internationalized?
  - markdown cells
  - code cells (e.g. chart labels, etc.)
  - metadata fields (title, etc)
- what does it get me?
  - metadata/SEO flagging
  - output formats (multiple `ipynb`, single `html`, multiple `html`)
- low-friction ways to propose/review/iterate/accept new translations (non-developers)

**Comment by rgbkrk** [comment] 2017-08-28 14:18
Spark UI

**Comment by bollwyvl** [comment] 2017-08-28 14:21
UI, Metadata and Tools for Richer Layouts

> continuing [this JEP](https://github.com/jupyter/enhancement-proposals/pull/15), [this discussion](https://github.com/jupyterlab/jupyterlab/issues/1640), RISE, nbpresent

- what to make?
  - posters
  - slides
  - dashboards
  - multi-page documents, a la bookbook, multirise, etc.
  - apps
- what to consume?
  - any mime you can render!
  - multiple notebooks, etc.
- what else?
  - layers
  - archival output (i.e. DOM-based PDF, e.g. chrome-headless
  - themes

**Comment by rgbkrk** [comment] 2017-08-28 14:22
# Resource Info Request

This started out as a little discussion in https://github.com/jupyter/jupyter/issues/264 at the last meetings. Now to follow up!

---------------------------------

When working in a jupyter environment, it would be helpful to see current resource usage

* CPU(s)
* Memory of the system
* Memory of the current kernel

Beyond that, people need information from libraries. Taking Spark as an example, they want to know several fields:

* Spark UI (string - URL)
* Memory on executors
* State of executors (?)
* Spark Version (string)
* Hadoop Version (string)

**Comment by minrk** [comment] 2017-08-28 14:30
display-data cell type: https://github.com/jupyter/notebook/issues/1123

**Comment by ellisonbg** [comment] 2017-08-28 14:53
Jupyter Markdown syntax:

At last team meeting we discussed doing some research to understand the precise markdown syntax that the classic notebook supports. We have started this work by creating notebooks with the CommonMark test suite. We currently don't pass much of it :( 

How should we proceed?

**Comment by ivanov** [comment] 2017-08-28 14:56
Kernel testing (validation, infrastructure, etc)

**Comment by ellisonbg** [comment] 2017-08-28 14:56
Where do we want to be in 3 years? Vision, strategy, big picture.

**Comment by choldgraf** [comment] 2017-08-28 15:01
re: @ellisonbg 's comment, specifically the topic of striking a balance between the enterprise/larger business community, and the more "open-sourcey", small-business, or academic community

**Comment by rgbkrk** [comment] 2017-08-28 15:41
Maintainer roundup

* Archiving (new hidden feature on GitHub), rather than jupyter-attic
* Current workflows

(Feel free to edit the above if you think of other subtopics)

**Comment by willingc** [comment] 2017-08-28 15:42
Follow up from the Education BOF at JupyterCon. Should we create a repo with initial invites to the attendees from the BOF to share issues (q&a) and content questions re: teaching. Perhaps initially make it private (so that there can be more discussion and deeper questions). Follow up from discussion with Lorena and Jess.

**Comment by willingc** [comment] 2017-08-28 15:45
Adding a Code of Conduct doc to each repo since GitHub is now tracking Community Insights (which new contributors look at). The doc could be simply a link to the document on the governance repo. I believe Libraries.io also tracks which projects have a CoC in the repo.

**Comment by rgbkrk** [comment] 2017-08-28 16:50
[VDOM Mimetype](https://github.com/nteract/nteract/pull/1866)

**Comment by DTAIEB** [comment] 2017-08-28 16:55
Dashboards: design and publish to web

**Comment by Carreau** [comment] 2017-08-28 16:57
Dev ops / maintnance / deprecate repo that are not maintained etc...

**Comment by Carreau** [comment] 2017-08-28 16:58
Communication in general, keeping blog and other communication channels, weekly summary up to date.

**Comment by Carreau** [comment] 2017-08-28 16:59
Jupyter Orange M&M's, and other swag.

**Comment by mpacer** [comment] 2017-08-28 17:10
package for multi-notebook publishing 

(Highly configurable, in analogy to nbconvert)

**Comment by mpacer** [comment] 2017-08-28 17:18
Mathjax and DOM safe equation rendering

**Comment by mpacer** [comment] 2017-08-28 17:20
Reproducible publications & connections to publishers and conferences, proceedings, &c.

**Comment by damianavila** [comment] 2017-10-04 16:02
Closing this one, there is no reason to keep it open now, IMHO.

**Closed by damianavila** 2017-10-04 16:02 UTC
